### ISSUE TITLE
Handle Outlook Clients

### ISSUE THREAD

**Issue by parkinsona** [DannyBoyNg/UserAgentService#4]
Is this service designed to determine outlook email clients?

For example for this userAgent : 
Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.15225; Pro)

I would expect that it would return Outlook 2016.
It does identify that it is not a browser, but for my purposes I need to know it is Outlook 2016.

Not sure if this is something you'd add in or not.

**Comment by DannyBoyNg** [comment]
Please correct me if i'm wrong. Would the following be correct?

var ua = userAgentService.Parse("Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.15225; Pro)");

var isBrowser = ua.IsBrowser; // true. It is either a browser, robot or mobile, so I'm assuming browser would be true.
var isRobot = ua.IsRobot; // false
var isMobile = ua.IsMobile; // false

var platform = ua.Platform; // Windows 10
var bowser = ua.Browser; // Microsoft Outlook
var version = ua.BrowserVersion; // 16.0.15225, I can't do 2016 here because I can only use versions that are in the actual string. With platforms, it is a little different.
var mobile = ua.Mobile; // empty string
var robot = ua.Robot; // empty string

**Comment by parkinsona** [comment]
that's helpful, I'd still need to do a bit of work my side to translate that version to 2016.

**Comment by DannyBoyNg** [comment]
A new version of the NuGet package has been released that can detect Microsoft Outlook. The new version is 1.1.1
